import React from 'react'
import Banner from './banner/Banner'

const page = () => {
  return (
    <div>
      <Banner/>
      <h1>This is About page</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Assumenda fuga magnam repellendus corporis in aut quaerat nemo cum ducimus atque. Temporibus dolor molestiae recusandae? Enim tenetur minima illum non pariatur. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aspernatur iste, magni nam, accusamus assumenda laboriosam molestias sunt est voluptatem, quis ad officia at vitae illum modi corporis ducimus? Sunt, accusantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam quibusdam, expedita natus illo debitis consectetur a mollitia exercitationem tempore vero ratione tenetur magni aliquid officia obcaecati enim, labore fugit doloribus!</p>
    </div>
  )
}

export default page
