// import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'

// import "./styles/globals.css";
import Header from './components/layout/Header/Header'
import Footer from './components/layout/Footer/Footer'
import "./styles/globals.css";
import "./styles/colors/colors.css";
import "./styles/base/base.css";
import "./styles/fonts/fonts.css";

// local custom font
const myFont = localFont({
  src: [
    {
      // path: '../public/site-fonts/Avenir/webFonts/AvenirLTPro-Medium/font.woff2',
      path: './fonts/Avenir/webFonts/AvenirLTPro-Medium/font.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Avenir/webFonts/AvenirLTPro-Black/font.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--my-font',
})
// local custom font

export const metadata = {
  title: "PMI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body style={{ fontFamily: "'MyFont', 'MyFont Fallback', sans-serif" }}>
        <div className="dialog-off-canvas-main-canvas">
        <Header/>
        {children}
        <Footer/>

        </div>
      </body>
    </html>
  );
}
